# Generated by Django 4.2 on 2023-04-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=60)),
                ('postalcode', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'localities',
            },
        ),
    ]
