# Generated by Django 4.2 on 2023-05-02 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0002_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Locality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postal_code", models.CharField(max_length=60)),
                ("locality", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "localities",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=60, unique=True)),
                ("designation", models.CharField(max_length=60)),
                ("address", models.CharField(max_length=255)),
                ("website", models.CharField(max_length=255, null=True)),
                ("phone", models.CharField(max_length=30, null=True)),
                (
                    "locality",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locations",
                        to="catalogue.locality",
                    ),
                ),
            ],
            options={
                "db_table": "locations",
            },
        ),
    ]
